function $(i){return document.getElementById(i)}
function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
var CATS=[["water","Water",.20,"💧",/पानी|नल|हैंडपंप|नलकूप|जल\b|pani|water|\bnal\b|handpump|tap/i,"Inspect handpump/pipeline; apply under Jal Jeevan Mission"],["road","Roads",.15,"🛣️",/सड़क|गड्ढ|रोड|पुल|road|pothole/i,"Repair the road; apply under PMGSY"],["garbage","Garbage",.15,"🗑️",/कचरा|कूड़ा|गंदगी|नाली|सफाई|garbage|kachra|drain|waste/i,"Arrange waste collection and drain cleaning (Swachh Bharat Gramin)"],["light","Streetlights",.10,"💡",/बिजली|लाइट|बल्ब|खंभा|street ?light|bijli|light/i,"Repair or install streetlights; check power supply"],["crops","Crops",.15,"🌾",/फसल|खेत|खेती|कीड़|बीज|सिंचाई|crop|fasal|kheti|irrigation/i,"Agriculture officer visit; PM-Kisan / irrigation support"],["health","Healthcare",.15,"🏥",/अस्पताल|डॉक्टर|दवा|दवाई|स्वास्थ्य|बीमार|hospital|doctor|dawa|medicine/i,"Arrange a health camp / visit to the nearest health centre"],["edu","Education",.10,"📚",/स्कूल|पढ़ाई|शिक्षक|इंटरनेट|किताब|school|internet|teacher/i,"Report to the school education office; Samagra Shiksha support"]];
var V=[{n:"Nipaniya Kalan",pop:3960,brg:0,d:0},{n:"Lasudiya Sukha",pop:1200,brg:225,d:3.14},{n:"Baddalpur",pop:1500,brg:45,d:3.17},{n:"Husainpur Khedi",pop:900,brg:270,d:3.46},{n:"Shiv Khedi",pop:1100,brg:135,d:3.93}];
var ST=["Reported","Verified","Forwarded to Panchayat","In Progress","Resolved"],SC=["var(--mu)","var(--b)","var(--y)","var(--o)","var(--g)"];
var S={s:[],c:[]},fresh=true;try{var z=JSON.parse(localStorage.getItem("rdss2")||"null");if(z){S=z;fresh=false}}catch(e){}
function save(){try{localStorage.setItem("rdss2",JSON.stringify(S))}catch(e){}}
function cat(k){return CATS.filter(function(c){return c[0]==k})[0]}
function col(x){return x==null?"var(--mu)":x>=70?"var(--r)":x>=50?"var(--o)":x>=30?"var(--y)":"var(--g)"}
function lab(x){return x==null?"No data":x>=70?"Critical":x>=50?"High":x>=30?"Moderate":"Low"}
function lastS(v){var a=S.s.filter(function(x){return x.v==v});return a[a.length-1]}
function catSev(v,k){var s=lastS(v),sv=s?s.sev[k]:null,o=S.c.filter(function(c){return c.v==v&&c.c==k&&c.st<4}),cl=Math.min(100,o.reduce(function(a,c){return a+c.sev*20},0));if(sv==null&&!o.length)return null;return sv==null?cl:Math.round(.7*sv+.3*cl)}
function vScore(v){var t=0,w=0;CATS.forEach(function(c){var x=catSev(v,c[0]);if(x!=null){t+=x*c[2];w+=c[2]}});return w?Math.round(t/w):null}
function openN(v){return S.c.filter(function(c){return c.v==v&&c.st<4}).length}
function classify(t){var best=null,n=0;CATS.forEach(function(c){var m=t.match(new RegExp(c[4].source,"gi"));if(m&&m.length>n){n=m.length;best=c[0]}});var sv=2;if(/तीन दिन|कई दिन|हफ्त|महीने|days|weeks|month|दिनों/i.test(t))sv++;if(/बहुत|भारी|खतरनाक|urgent|severe|बच्चे|बीमार|दुर्घटना|accident/i.test(t))sv++;if(/बिल्कुल|कोई नहीं|बंद|नहीं आ|no water/i.test(t))sv++;return{c:best,s:Math.min(5,sv)}}
function demo(){var d=new Date().toISOString().slice(0,10),P={"Nipaniya Kalan":[70,45,55,30,40,60,25],"Lasudiya Sukha":[40,65,35,50,55,70,40],"Baddalpur":[25,30,20,20,35,35,20],"Husainpur Khedi":[80,70,60,55,50,75,55],"Shiv Khedi":[50,55,45,35,45,65,35]};S={s:[],c:[]};
 V.forEach(function(v){var sev={};CATS.forEach(function(c,i){sev[c[0]]=P[v.n][i]});S.s.push({v:v.n,by:"Demo",sev:sev,note:"",gps:"",t:d,demo:1})});
 [["Husainpur Khedi","water",4,"तीन दिन से हैंडपंप खराब है",1],["Lasudiya Sukha","road",3,"Potholes on the main road",0],["Nipaniya Kalan","garbage",3,"कचरा उठाने की व्यवस्था नहीं",2],["Husainpur Khedi","health",3,"Nearest clinic is too far for elders",0],["Shiv Khedi","light",2,"Two streetlights not working",3]].forEach(function(x){S.c.push({id:"C-"+String(S.c.length+1).padStart(3,"0"),v:x[0],c:x[1],sev:x[2],t:x[3],loc:"",by:"",img:"",st:x[4],demo:1})});save()}
if(fresh)demo();
// static content
$("nav").innerHTML='<b>🌾 Rural DSS</b>'+[["home","Home"],["problem","Problem"],["how","How it works"],["ai","AI"],["explorer","Map"],["demo","Live demo"],["arch","Tech"],["road","Roadmap"],["team","Team"]].map(function(n){return'<a href="#'+n[0]+'" data-p="'+n[0]+'">'+n[1]+"</a>"}).join("");
$("th").onclick=function(){var r=document.documentElement,d=r.dataset.theme?r.dataset.theme=="dark":matchMedia("(prefers-color-scheme:dark)").matches;r.dataset.theme=d?"light":"dark"};
$("prob").innerHTML=[["📒","Scattered records","Village problems live in registers, calls and memory. There is no single, searchable view."],["🕳️","No evidence","Complaints reach the Panchayat without photos, locations or severity, so they are easy to ignore."],["⚖️","No comparison","Nobody can compare nearby villages or decide where limited resources should go first."]].map(function(c){return'<div class="card h"><div class="ic">'+c[0]+"</div><h3>"+c[1]+'</h3><div class="mu">'+c[2]+"</div></div>"}).join("");
$("pipe").innerHTML=[["🚶","Field visit","Team surveys villages and photographs problems."],["📱","Data capture","Web form, GPS, photos, Hindi voice."],["🗄️","Database","Records stored by village, category and location."],["🧠","AI analysis","Classification, severity and priority scoring."],["🗺️","GIS dashboard","Maps, rankings and comparisons."],["🏛️","Panchayat action","Priority list with scheme suggestions."]].map(function(c,i){return'<div class="st"><b>'+c[0]+"</b><strong>"+c[1]+'</strong><div class="mu">'+c[2]+"</div></div>"}).join("");
$("strip").innerHTML=[[5,"Villages studied"],[7,"Problem categories"],[5,"Working modules"],[9,"Step project plan"]].map(function(s){return'<div><b data-n="'+s[0]+'">0</b><span>'+s[1]+"</span></div>"}).join("");
$("mq").innerHTML=($("mq").dataset.x=["💧 Water","🛣️ Roads","🗑️ Garbage","💡 Streetlights","🌾 Crops","🏥 Healthcare","📚 Education"].map(function(x){return"<span>"+x+"</span>"}).join(""),$("mq").dataset.x+$("mq").dataset.x);
$("mq2").innerHTML=(function(){var h=["Python","FastAPI","PostgreSQL","PostGIS","React","Flutter","Leaflet","YOLO","OpenCV","Speech-to-Text","Firebase","scikit-learn"].map(function(x){return"<span>"+x+"</span>"}).join("");return h+h})();
$("wave").innerHTML=Array.apply(null,Array(26)).map(function(_,i){return'<i style="height:'+(10+Math.abs(Math.sin(i))*34)+"px;animation-delay:"+(i*.07)+'s"></i>'}).join("");
(function(){var r=classify("हमारे गाँव में तीन दिन से नल में पानी नहीं आ रहा");$("vchips").innerHTML='<span>Category: '+cat(r.c)[1]+"</span><span>Severity: "+r.s+"/5</span><span>Priority: "+(r.s>=4?"High":"Medium")+"</span>"})();
$("archd").innerHTML=[["Users",["Villager (Hindi voice / text)","Survey team (photos, GPS)","Panchayat / Admin"]],["Application",["Web / Mobile app"]],["Backend",["REST APIs","Authentication & roles","Complaint & status engine"]],["AI services",["Computer vision","Speech + NLP","Severity & priority scoring"]],["Data & output",["PostgreSQL + PostGIS","Photo storage","GIS dashboard & reports"]]].map(function(r,i){return'<div style="display:flex;gap:8px;margin-bottom:6px"><div style="background:var(--dg);color:#fff;border-radius:10px;padding:10px;min-width:100px;display:grid;place-items:center;font-weight:700;font-size:13px;text-align:center">'+r[0]+'</div><div style="flex:1;display:flex;gap:8px;flex-wrap:wrap">'+r[1].map(function(x){return'<div class="card" style="flex:1;min-width:130px;padding:10px;text-align:center;font-size:13.5px;margin:0">'+x+"</div>"}).join("")+"</div></div>"}).join("");
$("tl").innerHTML=[["d","Problem identified","Seven categories scoped from the community needs."],["d","Study villages selected","Nipaniya Kalan and four nearby villages near VIT Bhopal."],["d","Prototype built","Survey, scoring, map, complaints, Hindi voice input."],["p","Field data and dataset","Collect real surveys and label photos."],["","AI development","Train and test pothole and garbage detection."],["","Backend and testing","Login, real database, real map tiles."],["","Second field visit","Validate with villagers and the Panchayat."],["","Final impact report","Technical, economic and societal feasibility."]].map(function(t){return'<div class="'+t[0]+'"><b>'+t[1]+'</b><div class="mu">'+t[2]+"</div></div>"}).join("");
$("tm").innerHTML=[["🧠","AI / ML","Computer vision and problem classification"],["🖥️","Full stack","Web and mobile application"],["⚙️","Backend","APIs, authentication, database"],["🗺️","GIS / analytics","Village maps and dashboards"],["🎤","AI / NLP","Hindi voice and complaint classification"],["📋","Research / data","Field surveys, dataset and testing"]].map(function(c){return'<div class="card h"><div class="ic">'+c[0]+"</div><h3>"+c[1]+'</h3><div class="mu">'+c[2]+"</div></div>"}).join("");
$("fe").innerHTML=[["Technical","Open-source stack"],["Economic","Low cost, free tools"],["Societal","Panchayat and villager use"],["Environmental","Waste and water focus"],["Demographic","Hindi, low-literacy friendly"],["Political","Supports scheme-based decisions"]].map(function(c){return'<div class="card"><b>'+c[0]+'</b><div class="mu">'+c[1]+"</div></div>"}).join("");
// forms
var VO=V.map(function(v){return'<option value="'+v.n+'">'+v.n+"</option>"}).join("");["sv","rv"].forEach(function(i){$(i).innerHTML=VO});
$("rc").innerHTML=CATS.map(function(c){return'<option value="'+c[0]+'">'+c[3]+" "+c[1]+"</option>"}).join("");$("rs").innerHTML=[1,2,3,4,5].map(function(i){return'<option'+(i==3?" selected":"")+">"+i+"</option>"}).join("");
$("sf").innerHTML=CATS.map(function(c){return'<label>'+c[3]+" "+c[1]+': <b id="o_'+c[0]+'">0</b></label><input type="range" min="0" max="100" value="0" data-k="'+c[0]+'">'}).join("");
$("sf").oninput=function(e){if(e.target.dataset.k)$("o_"+e.target.dataset.k).textContent=e.target.value};
function gps(i,b){b.onclick=function(){if(!navigator.geolocation){b.textContent="GPS not available";return}b.textContent="Locating...";navigator.geolocation.getCurrentPosition(function(p){i.value=p.coords.latitude.toFixed(5)+", "+p.coords.longitude.toFixed(5);b.textContent="📍 Done"},function(){b.textContent="Could not get GPS"})}}gps($("sgps"),$("gps"));gps($("rl"),$("rgps"));
function msg(id,t){var o=$(id);o.style.display="block";o.textContent=t}
$("ssave").onclick=function(){var sev={};document.querySelectorAll("#sf input").forEach(function(i){sev[i.dataset.k]=+i.value});S.s.push({v:$("sv").value,by:$("sn").value,sev:sev,note:$("snote").value,gps:$("sgps").value,t:new Date().toISOString().slice(0,10)});save();rAll();msg("sok","Survey saved for "+$("sv").value+". Scores and map updated.")};
$("cls").onclick=function(){var r=classify($("rt").value);if(r.c){$("rc").value=r.c;$("rs").value=r.s;$("clsnote").textContent="Suggested: "+cat(r.c)[1]+", severity "+r.s+"/5 (keyword-based). You can edit both."}else $("clsnote").textContent="No category detected. Please choose one."};
var SR=window.SpeechRecognition||window.webkitSpeechRecognition,rec=null;
$("mic").onclick=function(){var b=$("mic"),m=$("micmsg");if(!SR){m.textContent="Voice input needs Chrome. You can type instead.";return}if(rec){rec.stop();return}rec=new SR();rec.lang="hi-IN";b.classList.add("rec");b.textContent="⏹ Listening...";m.textContent="";
 rec.onresult=function(e){$("rt").value=($("rt").value+" "+e.results[0][0].transcript).trim();$("cls").click()};rec.onerror=function(e){m.textContent="Mic error: "+e.error+". Allow microphone or type instead."};rec.onend=function(){rec=null;b.classList.remove("rec");b.textContent="🎤 Speak in Hindi"};rec.start()};
$("rf").onchange=function(){var f=this.files[0];window._img="";if(!f)return;var r=new FileReader();r.onload=function(){var im=new Image();im.onload=function(){var k=Math.min(1,300/im.width),c=document.createElement("canvas");c.width=im.width*k;c.height=im.height*k;c.getContext("2d").drawImage(im,0,0,c.width,c.height);window._img=c.toDataURL("image/jpeg",.6)};im.src=r.result};r.readAsDataURL(f)};
$("rsub").onclick=function(){var t=$("rt").value.trim();if(!t){$("rt").focus();return}var id="C-"+String(S.c.length+1).padStart(3,"0");S.c.push({id:id,v:$("rv").value,c:$("rc").value,sev:+$("rs").value,t:t,loc:$("rl").value,by:$("rn").value,img:window._img||"",st:0});save();$("rt").value="";$("rf").value="";window._img="";rAll();msg("rok","Complaint "+id+" registered. See it in the Tracker tab.")};
$("reset").onclick=function(){demo();rAll()};$("clear").onclick=function(){if(confirm(tr("Delete all data saved in this browser?"))){S={s:[],c:[]};save();rAll()}};
// tabs
var TB=[["rank","Dashboard"],["survey","Field survey"],["report","Report problem"],["track","Tracker"]];
$("tabs").innerHTML=TB.map(function(t){return'<button data-t="'+t[0]+'">'+t[1]+"</button>"}).join("");
function tab(id){document.querySelectorAll(".tp").forEach(function(e){e.classList.toggle("on",e.id=="t-"+id)});document.querySelectorAll("#tabs button").forEach(function(b){b.classList.toggle("on",b.dataset.t==id)})}
$("tabs").onclick=function(e){if(e.target.dataset.t)tab(e.target.dataset.t)};tab("rank");
$("adm").onchange=rTrack;
$("kb").onclick=function(e){var id=e.target.dataset.adv;if(!id)return;var c=S.c.filter(function(x){return x.id==id})[0];c.st++;save();rAll()};
function rTrack(){var a=$("adm").checked;$("kb").innerHTML=ST.map(function(s,i){var L=S.c.filter(function(c){return c.st==i}).sort(function(a,b){return b.sev-a.sev});return'<div class="col"><h4><span style="color:'+SC[i]+'">● '+s+'</span><span class="mu">'+L.length+"</span></h4>"+L.map(function(c){var k=cat(c.c);return'<div class="kc"><b>'+c.id+" · "+k[3]+" "+k[1]+"</b>"+(c.demo?' <span class="pill">DEMO</span>':"")+'<div class="mu">'+esc(c.v)+" · severity "+c.sev+"/5</div><div"+(c.demo?"":" data-u")+">"+esc(c.t)+"</div>"+(c.loc?'<div class="mu" data-u>📍 '+esc(c.loc)+"</div>":"")+(c.img?'<img src="'+c.img+'" alt="">':"")+'<div class="mu" style="margin-top:4px">💡 '+k[5]+"</div>"+(a&&c.st<4?'<div style="margin-top:6px"><button class="btn s" data-adv="'+c.id+'">→ '+ST[c.st+1]+"</button></div>":"")+"</div>"}).join("")+"</div>"}).join("")}
function rRank(){var R=V.map(function(v){return{v:v,s:vScore(v.n)}}).sort(function(a,b){return(b.s==null?-1:b.s)-(a.s==null?-1:a.s)});
 $("rank").innerHTML=R.map(function(r,i){var top=null;CATS.forEach(function(c){var x=catSev(r.v.n,c[0]);if(x!=null&&(!top||x>top[1]))top=[c,x]});return'<div class="card" style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap"><b>'+(i+1)+". "+r.v.n+'</b><span class="pill" style="background:'+col(r.s)+'">'+(r.s==null?"No data":r.s+" · "+lab(r.s))+'</span></div><div class="mu">Most serious: '+(top?top[0][3]+" "+top[0][1]+" ("+top[1]+")":"no data yet")+" · Open complaints: "+openN(r.v.n)+"</div>"+CATS.map(function(c){var x=catSev(r.v.n,c[0]);return'<div class="cb"><span>'+c[1]+'</span><div class="bar"><i style="width:'+(x||0)+"%;background:"+col(x)+'"></i></div><span>'+(x==null?"–":x)+"</span></div>"}).join("")+"</div>"}).join("");
 $("slist").innerHTML=S.s.length?'<table><tr><th>Date</th><th>Village</th><th>By</th>'+CATS.map(function(c){return"<th>"+c[1]+"</th>"}).join("")+"</tr>"+S.s.slice().reverse().slice(0,8).map(function(x){return"<tr><td>"+x.t+"</td><td>"+esc(x.v)+(x.demo?' <span class="pill">DEMO</span>':"")+"</td><td"+(x.demo?"":" data-u")+">"+esc(x.by)+"</td>"+CATS.map(function(c){return"<td>"+x.sev[c[0]]+"</td>"}).join("")+"</tr>"}).join("")+"</table>":'<span class="mu">No surveys yet.</span>';
 $("demonote").textContent=S.s.some(function(x){return x.demo})?"Showing sample data marked DEMO. Add your own surveys and complaints, or clear everything.":"Showing only data entered in this browser.";
 var sc=V.map(function(v){return vScore(v.n)}).filter(function(x){return x!=null}),avg=sc.length?Math.round(sc.reduce(function(a,b){return a+b},0)/sc.length):0,a=Math.PI*(1-avg/100);
 $("gauge").innerHTML='<path d="M20 110A90 90 0 0 1 200 110" fill="none" stroke="var(--bd)" stroke-width="16" stroke-linecap="round"/><path d="M20 110A90 90 0 0 1 '+(110+90*Math.cos(a)).toFixed(1)+" "+(110-90*Math.sin(a)).toFixed(1)+'" fill="none" stroke="'+col(avg)+'" stroke-width="16" stroke-linecap="round" style="animation:gx 1.2s both"/><text x="110" y="100" text-anchor="middle" style="font-size:34px;font-weight:800">'+avg+'</text><text x="110" y="122" text-anchor="middle">average · '+lab(avg)+"</text>";
 $("mini").innerHTML=R.map(function(r){return'<div class="cb" style="grid-template-columns:110px 1fr 30px"><span>'+r.v.n+'</span><div class="bar"><i style="width:'+(r.s||0)+"%;background:"+col(r.s)+'"></i></div><span>'+(r.s==null?"–":r.s)+"</span></div>"}).join("")}
// map + radar
var sel=0;
function rMap(){var h='<rect width="420" height="340" fill="none" stroke="var(--bd)" rx="12"/><path d="M0 250Q90 215 170 262T330 236T420 262" stroke="var(--b)" stroke-width="9" fill="none" opacity=".35"/><path d="M-10 90Q120 120 200 70T430 100" stroke="#b9a57a" stroke-width="5" fill="none" opacity=".5" stroke-dasharray="10 6"/>',cx=210,cy=170,k=42;
 V.forEach(function(v){var r=v.brg*Math.PI/180;v.x=cx+v.d*k*Math.sin(r);v.y=cy-v.d*k*Math.cos(r);if(v.d)h+='<line x1="'+cx+'" y1="'+cy+'" x2="'+v.x+'" y2="'+v.y+'" stroke="var(--ac)" stroke-dasharray="4" opacity=".5"/><text x="'+((v.x+cx)/2)+'" y="'+((v.y+cy)/2-3)+'" text-anchor="middle" style="opacity:.7">'+v.d+" km</text>"});
 V.forEach(function(v,i){var s=vScore(v.n),r=v.d?15:19,o=S.c.filter(function(c){return c.v==v.n&&c.st<4});h+='<g data-i="'+i+'" style="cursor:pointer"><circle cx="'+v.x+'" cy="'+v.y+'" r="'+r+'" fill="'+col(s)+'" opacity=".35"><animate attributeName="r" values="'+r+";"+(r+11)+";"+r+'" dur="2.6s" repeatCount="indefinite"/><animate attributeName="opacity" values=".35;0;.35" dur="2.6s" repeatCount="indefinite"/></circle><circle cx="'+v.x+'" cy="'+v.y+'" r="'+r+'" fill="'+col(s)+'" stroke="'+(i==sel?"var(--tx)":"none")+'" stroke-width="2.5"/><text x="'+v.x+'" y="'+(v.y+4)+'" text-anchor="middle" style="fill:#fff;font-weight:800">'+(s==null?"":s)+"</text>"+o.map(function(c,j){var an=(j*1.9+i)*1;return'<circle cx="'+(v.x+Math.cos(an)*(r+9)).toFixed(1)+'" cy="'+(v.y+Math.sin(an)*(r+9)).toFixed(1)+'" r="4" fill="'+(c.sev>=4?"var(--r)":"var(--o)")+'" stroke="#fff"/>'}).join("")+'<text x="'+v.x+'" y="'+(v.y+r+22)+'" text-anchor="middle" style="font-weight:700">'+v.n+"</text></g>"});
 h+='<text x="14" y="24">N ↑</text><text x="14" y="330" style="opacity:.7">Kothri (town) ~12 km from Nipaniya Kalan</text>';$("map").innerHTML=h;
 var v=V[sel],s=vScore(v.n),pr=CATS.map(function(c){return[c,catSev(v.n,c[0])]}).filter(function(x){return x[1]!=null}).sort(function(a,b){return b[1]-a[1]}).slice(0,3);
 $("mt").textContent=v.n+" · "+(s==null?"No data":s+" ("+lab(s)+")");$("mi").innerHTML="Population "+v.pop+(v.n=="Nipaniya Kalan"?" (Census 2011)":" (to be verified)")+" · Open complaints: "+openN(v.n);
 $("mrec").innerHTML=pr.length?'<div style="margin-top:8px"><b>Recommended actions</b><ul>'+pr.map(function(x){return"<li>"+x[0][3]+" <b>"+x[0][1]+" ("+x[1]+")</b>: "+x[0][5]+"</li>"}).join("")+"</ul></div>":"";
 var R=82,c=[120,112],pts=CATS.map(function(q,i){var an=-Math.PI/2+i*2*Math.PI/7,x=catSev(v.n,q[0])||0;return[c[0]+Math.cos(an)*R*x/100,c[1]+Math.sin(an)*R*x/100,an,q]}),rd="";
 [.33,.66,1].forEach(function(f){rd+='<polygon points="'+CATS.map(function(q,i){var an=-Math.PI/2+i*2*Math.PI/7;return(c[0]+Math.cos(an)*R*f).toFixed(1)+","+(c[1]+Math.sin(an)*R*f).toFixed(1)}).join(" ")+'" fill="none" stroke="var(--bd)"/>'});
 rd+='<polygon points="'+pts.map(function(p){return p[0].toFixed(1)+","+p[1].toFixed(1)}).join(" ")+'" fill="'+col(s)+'" fill-opacity=".35" stroke="'+col(s)+'" stroke-width="2"/>'+pts.map(function(p){return'<text x="'+(c[0]+Math.cos(p[2])*(R+16)).toFixed(1)+'" y="'+(c[1]+Math.sin(p[2])*(R+14)+4).toFixed(1)+'" text-anchor="middle">'+p[3][3]+"</text>"}).join("");$("radar").innerHTML=rd}
$("map").onclick=function(e){var g=e.target.closest("g");if(g){sel=+g.dataset.i;rMap()}};
function rAll(){rRank();rTrack();rMap()}
rAll();
// effects
$("home").querySelectorAll("#scene");var W=["Water","Roads","Garbage","Streetlights","Crops","Healthcare","Education"],wi=0;setInterval(function(){var e=$("word");e.style.opacity=0;setTimeout(function(){wi=(wi+1)%W.length;e.textContent=W[wi];e.style.opacity=1},300)},2200);
function count(el,to){var s=null;function f(ts){s=s||ts;var k=Math.min(1,(ts-s)/1100);el.textContent=Math.round(to*k);if(k<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
var io;try{io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}})},{threshold:.08});document.querySelectorAll(".rv").forEach(function(e){io.observe(e)});var so=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){document.querySelectorAll("#nav a").forEach(function(a){a.classList.toggle("on",a.dataset.p==e.target.id)});if(e.target.id=="home"&&!window._c){window._c=1;document.querySelectorAll("[data-n]").forEach(function(x){count(x,+x.dataset.n)})}}})},{rootMargin:"-40% 0px -55% 0px"});["home","problem","how","ai","explorer","demo","arch","road","team"].forEach(function(p){so.observe($(p))});var co=new IntersectionObserver(function(es){if(es[0].isIntersecting&&!window._c){window._c=1;document.querySelectorAll("[data-n]").forEach(function(x){count(x,+x.dataset.n)})}});co.observe($("strip"))}catch(e){document.querySelectorAll(".rv").forEach(function(e){e.classList.add("in")});document.querySelectorAll("[data-n]").forEach(function(x){x.textContent=x.dataset.n})}
window.addEventListener("scroll",function(){var d=document.documentElement,y=d.scrollTop;$("pg").style.width=(y/(d.scrollHeight-d.clientHeight)*100)+"%";if(y<700)$("scene").style.transform="translateY("+y*.12+"px)"},{passive:true});
// ===== language toggle (EN / हिं) =====
var HI=[["Rural DSS","ग्रामीण DSS"],["Home","होम"],["Problem","समस्या"],["How it works","यह कैसे काम करता है"],["Map","नक्शा"],["Live demo","लाइव डेमो"],["Tech","तकनीक"],["Roadmap","रोडमैप"],["Team","टीम"],
["VIT Bhopal","वीआईटी भोपाल"],["📍 5 villages mapped","📍 5 गाँवों का नक्शा"],["🎤 Hindi voice complaints","🎤 हिंदी आवाज़ में शिकायतें"],["📊 Priority score 0–100","📊 प्राथमिकता स्कोर 0–100"],["Finding rural problems early.","ग्रामीण समस्याओं को जल्दी पहचानें।"],["Fix first:","सबसे पहले ठीक करें:"],
["A decision support platform that collects village-level data, detects problems with AI, ranks nearby villages on a GIS map and sends evidence-backed priorities to the Panchayat.","गाँव स्तर का डेटा जुटाने, AI से समस्याएँ पहचानने, GIS नक्शे पर आसपास के गाँवों को रैंक करने और प्रमाण सहित प्राथमिकताएँ पंचायत तक पहुँचाने वाला निर्णय सहायता मंच।"],["Try the live demo","लाइव डेमो आज़माएँ"],["Explore the map","नक्शा देखें"],
["Villages studied","अध्ययन किए गए गाँव"],["Problem categories","समस्या श्रेणियाँ"],["Working modules","काम करते मॉड्यूल"],["Step project plan","चरणों की परियोजना योजना"],
["Water","पानी"],["Roads","सड़क"],["Garbage","कचरा"],["Streetlights","स्ट्रीटलाइट"],["Crops","फसल"],["Healthcare","स्वास्थ्य सेवा"],["Education","शिक्षा"],
["The problem","समस्या"],["Villages have problems. Decisions lack evidence.","गाँवों में समस्याएँ हैं, पर निर्णयों के पास प्रमाण नहीं।"],["Problems are scattered across paper registers and phone calls. Nobody can see which village needs what first.","समस्याएँ कागज़ी रजिस्टरों और फ़ोन कॉल में बिखरी हैं। कोई नहीं देख पाता कि किस गाँव को सबसे पहले क्या चाहिए।"],["Scattered records","बिखरे हुए रिकॉर्ड"],["Village problems live in registers, calls and memory. There is no single, searchable view.","गाँव की समस्याएँ रजिस्टरों, कॉल और यादों में रहती हैं। कोई एक खोजने योग्य तस्वीर नहीं है।"],["No evidence","कोई प्रमाण नहीं"],["Complaints reach the Panchayat without photos, locations or severity, so they are easy to ignore.","शिकायतें बिना फ़ोटो, स्थान या गंभीरता के पंचायत तक पहुँचती हैं, इसलिए आसानी से अनदेखी हो जाती हैं।"],["No comparison","कोई तुलना नहीं"],["Nobody can compare nearby villages or decide where limited resources should go first.","आसपास के गाँवों की तुलना या सीमित संसाधन पहले कहाँ लगें, यह तय करना संभव नहीं।"],
["From field visit to Panchayat action","फ़ील्ड विज़िट से पंचायत की कार्रवाई तक"],["A complete pipeline built on problems discovered in real nearby villages.","आसपास के असली गाँवों में मिली समस्याओं पर बना पूरा प्रवाह।"],["Field visit","फ़ील्ड विज़िट"],["Team surveys villages and photographs problems.","टीम गाँवों का सर्वे करती है और समस्याओं की फ़ोटो लेती है।"],["Data capture","डेटा संग्रह"],["Web form, GPS, photos, Hindi voice.","वेब फ़ॉर्म, GPS, फ़ोटो, हिंदी आवाज़।"],["Database","डेटाबेस"],["Records stored by village, category and location.","रिकॉर्ड गाँव, श्रेणी और स्थान के अनुसार सुरक्षित।"],["AI analysis","AI विश्लेषण"],["Classification, severity and priority scoring.","वर्गीकरण, गंभीरता और प्राथमिकता स्कोर।"],["GIS dashboard","GIS डैशबोर्ड"],["Maps, rankings and comparisons.","नक्शे, रैंकिंग और तुलना।"],["Panchayat action","पंचायत की कार्रवाई"],["Priority list with scheme suggestions.","योजना सुझावों के साथ प्राथमिकता सूची।"],
["Intelligence","बुद्धिमत्ता"],["AI that understands photos and Hindi","AI जो फ़ोटो और हिंदी समझता है"],["Three modules turn raw reports into a priority list.","तीन मॉड्यूल कच्ची रिपोर्टों को प्राथमिकता सूची में बदलते हैं।"],["Computer vision","कंप्यूटर विज़न"],["Planned","नियोजित"],["Working","कार्यरत"],["Pothole · HIGH","गड्ढा · गंभीर"],["Illustration of the planned output: detect potholes, garbage and waterlogging in field photos and rate severity. Model training is Phase II.","नियोजित आउटपुट का चित्र: फ़ील्ड फ़ोटो में गड्ढे, कचरा और जलभराव पहचानना और गंभीरता आँकना। मॉडल प्रशिक्षण दूसरे चरण में होगा।"],["Hindi voice complaints","हिंदी आवाज़ में शिकायतें"],["Category:","श्रेणी:"],["Severity:","गंभीरता:"],["Priority:","प्राथमिकता:"],["Medium","मध्यम"],["Speech to text in the browser, then a keyword classifier detects category and severity (computed live from the sentence above).","ब्राउज़र में आवाज़ से टेक्स्ट, फिर कीवर्ड वर्गीकारक श्रेणी और गंभीरता पहचानता है (ऊपर के वाक्य से लाइव गणना)।"],["Village priority score","गाँव प्राथमिकता स्कोर"],["Weighted by category, built from field-survey severity (70%) and open complaints (30%). Higher means more serious.","श्रेणी के भार से, फ़ील्ड सर्वे की गंभीरता (70%) और खुली शिकायतों (30%) से बना। अधिक का मतलब अधिक गंभीर।"],["average ·","औसत ·"],["GIS village comparison","GIS गाँव तुलना"],["Nearby villages ranked side by side, so limited resources go where the need is greatest.","आसपास के गाँव साथ-साथ रैंक किए जाते हैं, ताकि सीमित संसाधन सबसे ज़्यादा ज़रूरत वाली जगह लगें।"],
["Village explorer","गाँव एक्सप्लोरर"],["Tap a village. Colour shows priority, the number shows open complaints, and the radar chart shows what is wrong.","किसी गाँव पर टैप करें। रंग प्राथमिकता, संख्या खुली शिकायतें और रडार चार्ट समस्याएँ दिखाता है।"],["Critical","गंभीर"],["High","उच्च"],["Moderate","मध्यम"],["Low","कम"],["Water body (illustrative)","जल स्रोत (चित्रात्मक)"],["● small dot = open complaint","● छोटा बिंदु = खुली शिकायत"],["Schematic map. Distances are real aerial distances from Nipaniya Kalan, not to scale.","योजनाबद्ध नक्शा। दूरियाँ निपानिया कलां से असली हवाई दूरी हैं, पैमाने पर नहीं।"],["Select a village","गाँव चुनें"],["Tap a village on the map.","नक्शे पर किसी गाँव पर टैप करें।"],["Kothri (town) ~12 km from Nipaniya Kalan","कोठरी (कस्बा) निपानिया कलां से ~12 किमी"],["km","किमी"],["Population","जनसंख्या"],["(Census 2011)","(जनगणना 2011)"],["(to be verified)","(सत्यापित किया जाना है)"],["Open complaints:","खुली शिकायतें:"],["Recommended actions","अनुशंसित कार्रवाइयाँ"],
["Inspect handpump/pipeline; apply under Jal Jeevan Mission","हैंडपंप/पाइपलाइन की जाँच करें; जल जीवन मिशन के तहत आवेदन करें"],["Repair the road; apply under PMGSY","सड़क की मरम्मत करें; PMGSY के तहत आवेदन करें"],["Arrange waste collection and drain cleaning (Swachh Bharat Gramin)","कचरा संग्रह और नाली सफ़ाई की व्यवस्था करें (स्वच्छ भारत ग्रामीण)"],["Repair or install streetlights; check power supply","स्ट्रीटलाइट की मरम्मत या स्थापना करें; बिजली आपूर्ति जाँचें"],["Agriculture officer visit; PM-Kisan / irrigation support","कृषि अधिकारी का दौरा; पीएम-किसान / सिंचाई सहायता"],["Arrange a health camp / visit to the nearest health centre","स्वास्थ्य शिविर / निकटतम स्वास्थ्य केंद्र का दौरा कराएँ"],["Report to the school education office; Samagra Shiksha support","विद्यालय शिक्षा कार्यालय को सूचित करें; समग्र शिक्षा सहायता"],
["Use it right here","यहीं इस्तेमाल करें"],["Everything below works. Enter a survey, report a problem by voice or text, and watch scores and the map update.","नीचे सब कुछ काम करता है। सर्वे दर्ज करें, आवाज़ या टेक्स्ट से समस्या दर्ज करें और स्कोर व नक्शा अपडेट होते देखें।"],["Showing sample data marked DEMO. Add your own surveys and complaints, or clear everything.","डेमो चिह्नित नमूना डेटा दिख रहा है। अपने सर्वे और शिकायतें जोड़ें, या सब कुछ साफ़ करें।"],["Showing only data entered in this browser.","केवल इसी ब्राउज़र में दर्ज डेटा दिख रहा है।"],["Dashboard","डैशबोर्ड"],["Field survey","फ़ील्ड सर्वे"],["Report problem","समस्या दर्ज करें"],["Tracker","ट्रैकर"],["Most serious:","सबसे गंभीर:"],["no data yet","अभी कोई डेटा नहीं"],["No data","कोई डेटा नहीं"],["Village *","गाँव *"],["Village","गाँव"],["Surveyor","सर्वेयर"],["Rate each problem 0 (none) to 100 (very severe).","हर समस्या को 0 (कोई नहीं) से 100 (बहुत गंभीर) तक आँकें।"],["Notes","टिप्पणियाँ"],["Location / landmark","स्थान / पहचान"],["Location","स्थान"],["📍 Use my GPS","📍 मेरा GPS इस्तेमाल करें"],["Save survey","सर्वे सहेजें"],["Survey saved for","सर्वे सहेजा गया:"],[". Scores and map updated.",". स्कोर और नक्शा अपडेट हुए।"],["Saved surveys","सहेजे गए सर्वे"],["Date","तारीख"],["By","द्वारा"],["No surveys yet.","अभी कोई सर्वे नहीं।"],["DEMO","डेमो"],["Demo","डेमो"],
["Your name (optional)","आपका नाम (वैकल्पिक)"],["Describe the problem (Hindi or English)","समस्या का वर्णन करें (हिंदी या अंग्रेज़ी)"],["🎤 Speak in Hindi","🎤 हिंदी में बोलें"],["Detect category & severity","श्रेणी और गंभीरता पहचानें"],["Category (editable)","श्रेणी (बदल सकते हैं)"],["Severity 1–5 (editable)","गंभीरता 1–5 (बदल सकते हैं)"],["Suggested by a keyword-based classifier. Please check before submitting.","कीवर्ड-आधारित वर्गीकारक द्वारा सुझाया गया। भेजने से पहले जाँच लें।"],["Suggested:","सुझाव:"],[", severity",", गंभीरता"],["(keyword-based). You can edit both.","(कीवर्ड-आधारित)। आप दोनों बदल सकते हैं।"],["No category detected. Please choose one.","कोई श्रेणी नहीं मिली। कृपया एक चुनें।"],["📍 Tag my GPS","📍 मेरा GPS टैग करें"],["Photo (optional)","फ़ोटो (वैकल्पिक)"],["Submit complaint","शिकायत भेजें"],["Complaint","शिकायत"],["registered. See it in the Tracker tab.","दर्ज हुई। इसे ट्रैकर टैब में देखें।"],["Voice input needs Chrome. You can type instead.","आवाज़ इनपुट के लिए Chrome चाहिए। आप टाइप कर सकते हैं।"],["Mic error:","माइक त्रुटि:"],[". Allow microphone or type instead.",". माइक्रोफ़ोन की अनुमति दें या टाइप करें।"],["⏹ Listening...","⏹ सुन रहा है..."],["Locating...","स्थान खोज रहा है..."],["📍 Done","📍 हो गया"],["GPS not available","GPS उपलब्ध नहीं"],["Could not get GPS","GPS नहीं मिला"],
["Panchayat / Admin mode (move complaints to the next stage)","पंचायत / एडमिन मोड (शिकायतों को अगले चरण में ले जाएँ)"],["Panchayat / Admin","पंचायत / एडमिन"],["Forwarded to Panchayat","पंचायत को भेजा गया"],["Reported","दर्ज"],["Verified","सत्यापित"],["In Progress","कार्य जारी"],["Resolved","हल हुआ"],["Severity","गंभीरता"],["severity","गंभीरता"],["Priority","प्राथमिकता"],["Panchayat","पंचायत"],["Reload sample data","नमूना डेटा फिर लोड करें"],["Clear all data","सारा डेटा साफ़ करें"],["Delete all data saved in this browser?","इस ब्राउज़र में सहेजा गया सारा डेटा हटाएँ?"],
["Engineering","इंजीनियरिंग"],["Architecture & tech stack","आर्किटेक्चर और तकनीकी स्टैक"],["Layered design that moves from a browser prototype to a full backend in Phase II.","परतदार डिज़ाइन जो दूसरे चरण में ब्राउज़र प्रोटोटाइप से पूर्ण बैकएंड तक जाता है।"],["Users","उपयोगकर्ता"],["Application","एप्लिकेशन"],["Backend","बैकएंड"],["AI services","AI सेवाएँ"],["Data & output","डेटा और आउटपुट"],["Villager (Hindi voice / text)","ग्रामीण (हिंदी आवाज़ / टेक्स्ट)"],["Survey team (photos, GPS)","सर्वे टीम (फ़ोटो, GPS)"],["Web / Mobile app","वेब / मोबाइल ऐप"],["REST APIs","REST API"],["Authentication & roles","प्रमाणीकरण और भूमिकाएँ"],["Complaint & status engine","शिकायत और स्थिति इंजन"],["Speech + NLP","आवाज़ + NLP"],["Severity & priority scoring","गंभीरता और प्राथमिकता स्कोर"],["Photo storage","फ़ोटो भंडारण"],["GIS dashboard & reports","GIS डैशबोर्ड और रिपोर्ट"],
["Project timeline","परियोजना समयरेखा"],["Problem identified","समस्या की पहचान"],["Seven categories scoped from the community needs.","समुदाय की ज़रूरतों से सात श्रेणियाँ तय हुईं।"],["Study villages selected","अध्ययन गाँव चुने गए"],["Nipaniya Kalan and four nearby villages near VIT Bhopal.","वीआईटी भोपाल के पास निपानिया कलां और चार नज़दीकी गाँव।"],["Prototype built","प्रोटोटाइप तैयार"],["Survey, scoring, map, complaints, Hindi voice input.","सर्वे, स्कोरिंग, नक्शा, शिकायतें, हिंदी आवाज़ इनपुट।"],["Field data and dataset","फ़ील्ड डेटा और डेटासेट"],["Collect real surveys and label photos.","असली सर्वे जुटाना और फ़ोटो लेबल करना।"],["AI development","AI विकास"],["Train and test pothole and garbage detection.","गड्ढे और कचरे की पहचान का प्रशिक्षण और परीक्षण।"],["Backend and testing","बैकएंड और परीक्षण"],["Login, real database, real map tiles.","लॉगिन, असली डेटाबेस, असली नक्शा टाइल।"],["Second field visit","दूसरी फ़ील्ड विज़िट"],["Validate with villagers and the Panchayat.","ग्रामीणों और पंचायत के साथ सत्यापन।"],["Final impact report","अंतिम प्रभाव रिपोर्ट"],["Technical, economic and societal feasibility.","तकनीकी, आर्थिक और सामाजिक व्यवहार्यता।"],
["Team & impact","टीम और प्रभाव"],["Six roles, one goal","छह भूमिकाएँ, एक लक्ष्य"],["A student team building technology for the community.","समुदाय के लिए तकनीक बनाती एक छात्र टीम।"],["Computer vision and problem classification","कंप्यूटर विज़न और समस्या वर्गीकरण"],["Full stack","फुल स्टैक"],["Web and mobile application","वेब और मोबाइल एप्लिकेशन"],["APIs, authentication, database","API, प्रमाणीकरण, डेटाबेस"],["GIS / analytics","GIS / एनालिटिक्स"],["Village maps and dashboards","गाँव के नक्शे और डैशबोर्ड"],["Hindi voice and complaint classification","हिंदी आवाज़ और शिकायत वर्गीकरण"],["Research / data","शोध / डेटा"],["Field surveys, dataset and testing","फ़ील्ड सर्वे, डेटासेट और परीक्षण"],["Feasibility","व्यवहार्यता"],["Technical","तकनीकी"],["Open-source stack","ओपन-सोर्स स्टैक"],["Economic","आर्थिक"],["Low cost, free tools","कम लागत, मुफ़्त टूल"],["Societal","सामाजिक"],["Panchayat and villager use","पंचायत और ग्रामीणों का उपयोग"],["Environmental","पर्यावरण"],["Waste and water focus","कचरा और पानी पर ध्यान"],["Demographic","जनसांख्यिकीय"],["Hindi, low-literacy friendly","हिंदी, कम साक्षरता के अनुकूल"],["Political","राजनीतिक"],["Supports scheme-based decisions","योजना-आधारित निर्णयों में सहायक"],
["Technology for the last mile","अंतिम छोर तक तकनीक"],["Built at VIT Bhopal for the Engineering Projects in Community Service course.","समुदाय सेवा में इंजीनियरिंग परियोजनाएँ पाठ्यक्रम के लिए वीआईटी भोपाल में बनाया गया।"],["Open the live demo","लाइव डेमो खोलें"],["Rural Problem Detection and Decision Support System","ग्रामीण समस्या पहचान एवं निर्णय सहायता प्रणाली"],["Built by Sanskrati Gupta and team","निर्माता: संस्कृति गुप्ता और टीम"],["Sample data is marked DEMO","नमूना डेटा पर डेमो लिखा है"],["Hindi","हिंदी"],["English","अंग्रेज़ी"],
["Potholes on the main road","मुख्य सड़क पर गड्ढे"],["Nearest clinic is too far for elders","निकटतम क्लिनिक बुज़ुर्गों के लिए बहुत दूर है"],["Two streetlights not working","दो स्ट्रीटलाइट काम नहीं कर रही हैं"],
["Nipaniya Kalan","निपानिया कलां"],["Lasudiya Sukha","लसुड़िया सुखा"],["Baddalpur","बड्डालपुर"],["Husainpur Khedi","हुसैनपुर खेड़ी"],["Shiv Khedi","शिव खेड़ी"]];
HI.sort(function(a,b){return b[0].length-a[0].length});
var RX=HI.map(function(p){var e=p[0].replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),a=/^[A-Za-z]/.test(p[0]),z=/[A-Za-z]$/.test(p[0]);return{r:new RegExp((a?"(^|[^A-Za-z])":"")+e+(z?"(?![A-Za-z])":""),"g"),a:a,h:p[1]}});
var lang="en";try{lang=localStorage.getItem("rdsl")||"en"}catch(e){}
function trs(s){if(!/[A-Za-z]/.test(s))return s;RX.forEach(function(x){s=s.replace(x.r,function(m,p){return(x.a?p:"")+x.h})});return s}
function tr(s){return lang=="hi"?trs(s):s}
function skipN(n){var p=n.parentNode;return !p||/^(SCRIPT|STYLE|TEXTAREA)$/.test(p.nodeName)||(p.closest&&p.closest("[data-u]"))}
function tn(n){if(skipN(n))return;if(n.__o===undefined)n.__o=n.nodeValue;n.nodeValue=trs(n.__o)}
function allT(r){var w=document.createTreeWalker(r,4),n,a=[];while(n=w.nextNode())a.push(n);return a}
function applyL(){document.documentElement.lang=lang=="hi"?"hi":"en";var b=$("lt");b.dataset.l=lang;b.setAttribute("aria-checked",lang=="hi");
 document.title=lang=="hi"?"ग्रामीण समस्या पहचान एवं निर्णय सहायता प्रणाली":"Rural Problem Detection and Decision Support System";
 $("rt").placeholder=lang=="hi"?"हमारे गाँव में तीन दिन से नल में पानी नहीं आ रहा":"e.g. There has been no water in the tap for three days";
 allT(document.body).forEach(function(n){if(lang=="hi")tn(n);else if(n.__o!==undefined)n.nodeValue=n.__o})}
$("lt").onclick=function(){lang=lang=="hi"?"en":"hi";try{localStorage.setItem("rdsl",lang)}catch(e){}applyL()};
try{new MutationObserver(function(ms){if(lang!="hi")return;ms.forEach(function(m){m.addedNodes.forEach(function(a){if(a.nodeType==3)tn(a);else if(a.nodeType==1)allT(a).forEach(tn)})})}).observe(document.body,{childList:true,subtree:true})}catch(e){}
applyL();
